server:
  port: 7000
spring:
  application:
    name: eureka-client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # defaultZone: http://localhost:9000/eureka, http://localhost:10000/eureka # 注册中心地址
      defaultZone: http://guo:123@localhost:11000/eureka # 注册中心地址
