server:
  port: 1004
spring:
  application:
    name: eureka-client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       defaultZone: http://localhost:1001/eureka, http://localhost:1002/eureka # 注册中心地址
#      defaultZone: http://guo:123@localhost:1004/eureka # 注册中心地址
