server:
  port: 10000
service-url:
  user-service: http://localhost:2001
spring:
  cloud:
    gateway:
      routes:
        - id: path_route # \u8DEF\u7531\u7684 ID
          uri: ${service-url.user-service}/user/{id} # \u8981\u8F6C\u53D1\u7684\u8DEF\u7531\u5730\u5740
          predicates: # \u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531
            - Path=/user/{id}