server:
  port: 26000
spring:
  application:
    name: micro-oauth2-api
  cloud:
    nacos:
     discovery:
       server-addr: 1.15.156.232:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'