server:
  port: 11000
spring:
  application:
    name: eureka-server
  security:
    user:
      name: guo
      password: 123
eureka:
  instance:
    hostname: localhost # 指定主机地址
  client:
    fetch-registry: false # 指定是否从注册中心获取服务
    register-with-eureka: false # 指定是否将服务注册到注册中心
  server:
    enable-self-preservation: false # 关闭保护模式