server:
  port: 3000
spring:
  application:
    name: hystrix-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
    register-with-eureka: true
    fetch-registry: true
service-url:
  user-service: http://user-service
