server:
  port: 12000
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:11000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: admin-client.log # 开启日志监控
