server:
  port: 23000
spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 1.15.156.232:8848
        group: SEATA_GROUP
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://1.15.156.232:3306/seata-storage
logging:
  level:
    io:
      seata: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 1.15.156.232:8848
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 1.15.156.232:8848
      username: nacos
      password: nacos
  tx-service-group: my_test_tx_group # 配置事务分组