server:
  port: 2000
spring:
  application:
    name: ribbon-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0 # 设置 Sleuth 的抽样收集概率
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1000/eureka
service-url:
  user-service: http://user-service